backend:
  name: git-gateway
  branch: master # Branch to update

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:

  - name: "Main"
    label: "main"
    files:
      - label: "Autor info"
        name: "autorinfo"
        file: "src/data/author.json"
        fields:
#          - {label: Name, name: name, widget: string}
#          - {label: Occupation, name: occupation, widget: string}
          - {label: Location, name: location, widget: string}
          - label: "Avatar"
            name: "avatar"
            widget: "file"
            default: "avatar.png"
            media_library:
              config:
                multiple: false
#          - {label: Pronouns, name: pronouns, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Telephone, name: telephone, widget: string}
          - {label: website, name: website, widget: string}
          - label: Skills
            name: skills
            widget: list
            default: ["skill"]
#            fields:
#              - {label: skill, name: skill, widget: string}
          - label: Languages
            name: languages
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Level, name: level, widget: string}
          - label: Social
            name: social
            widget: list
            fields:
              - {label: name, name: name, widget: string}
              - {label: user, name: user, widget: string}
              - {label: url, name: url, widget: string}
      - label: "Localization js"
        name: "lacalize"
        file: "src/data/i18n/index.js"
        fields:
          - label: 'Code'
            name: 'code'
            widget: 'code'

  - name: "intro-en-GB"
    label: "Intro-english"
    file: "src/en-GB/entries/introduction.md"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "Post Body", name: "body", widget: "markdown"}
  - name: "works-en-GB"
    label: "Work-english"
    folder: "src/en-GB/entries/work"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "organization", name: "organization", widget: "string"}
      - {label: "organizationUrl", name: "organizationUrl", widget: "string"}
      - {label: "location", name: "location", widget: "string"}
      - {label: "start", name: "start", widget: "string"}
      - {label: "end", name: "end", widget: "string"}
      - {label: "Post Body", name: "body", widget: "markdown"}
  - name: "education-en-GB"
    label: "Education-english"
    folder: "src/en-GB/entries/education"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "organization", name: "organization", widget: "string"}
      - {label: "location", name: "location", widget: "string"}
      - {label: "start", name: "start", widget: "string"}
      - {label: "end", name: "end", widget: "string"}
  - name: "content-en-GB"
    label: "Content-english"
    folder: "src/en-GB/entries/content"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "Post Body", name: "body", widget: "markdown"}

  - name: "intro-es-ES"
    label: "Intro-english"
    file: "src/es-ES/entries/introduction.md"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "Post Body", name: "body", widget: "markdown"}
  - name: "works-es-ES"
    label: "Work-english"
    folder: "src/es-ES/entries/work"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "organization", name: "organization", widget: "string"}
      - {label: "organizationUrl", name: "organizationUrl", widget: "string"}
      - {label: "location", name: "location", widget: "string"}
      - {label: "start", name: "start", widget: "string"}
      - {label: "end", name: "end", widget: "string"}
      - {label: "Post Body", name: "body", widget: "markdown"}
  - name: "education-es-ES"
    label: "Education-english"
    folder: "src/es-ES/entries/education"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "organization", name: "organization", widget: "string"}
      - {label: "location", name: "location", widget: "string"}
      - {label: "start", name: "start", widget: "string"}
      - {label: "end", name: "end", widget: "string"}
  - name: "content-es-ES"
    label: "Content-english"
    folder: "src/es-ES/entries/content"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "Post Body", name: "body", widget: "markdown"}

  - name: "intro-ru-RU"
    label: "Intro-english"
    file: "src/ru-RU/entries/introduction.md"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "Post Body", name: "body", widget: "markdown"}
  - name: "works-ru-RU"
    label: "Work-english"
    folder: "src/ru-RU/entries/work"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "organization", name: "organization", widget: "string"}
      - {label: "organizationUrl", name: "organizationUrl", widget: "string"}
      - {label: "location", name: "location", widget: "string"}
      - {label: "start", name: "start", widget: "string"}
      - {label: "end", name: "end", widget: "string"}
      - {label: "Post Body", name: "body", widget: "markdown"}
  - name: "education-ru-RU"
    label: "Education-english"
    folder: "src/ru-RU/entries/education"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "organization", name: "organization", widget: "string"}
      - {label: "location", name: "location", widget: "string"}
      - {label: "start", name: "start", widget: "string"}
      - {label: "end", name: "end", widget: "string"}
  - name: "content-ru-RU"
    label: "Content-english"
    folder: "src/ru-RU/entries/content"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "Post Body", name: "body", widget: "markdown"}
