backend:
  name: git-gateway
  branch: master # Branch to update

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:

  - name: "Main"
    label: "main"
    files:
      - label: "Autor info"
        name: "autorinfo"
        file: "src/data/author.json"
        fields:
#          - {label: Name, name: name, widget: string}
#          - {label: Occupation, name: occupation, widget: string}
          - {label: Location, name: location, widget: string}
          - label: "Avatar"
            name: "avatar"
            widget: "file"
            default: "avatar.png"
            media_library:
              config:
                multiple: false
#          - {label: Pronouns, name: pronouns, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Telephone, name: telephone, widget: string}
          - {label: website, name: website, widget: string}
          - label: Skills
            name: skills
            widget: list
            default: ["skill"]
#            fields:
#              - {label: skill, name: skill, widget: string}
          - label: Languages
            name: languages
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Level, name: level, widget: string}
          - label: Social
            name: social
            widget: list
            fields:
              - {label: name, name: name, widget: string}
              - {label: user, name: user, widget: string}
              - {label: url, name: url, widget: string}
          - label: "Localization js"
            name: "lacalize"
            file: "src/data/i18n/index.js"
            fields:
              - label: 'Code'
                name: 'code'
                widget: 'code'
  - name: "Works-en-GB"
    label: "work-en"
    folder: "src/en-GB/entries/work"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "organization", name: "organization", widget: "string"}
      - {label: "organizationUrl", name: "organizationUrl", widget: "string"}
      - {label: "location", name: "location", widget: "string"}
      - {label: "start", name: "start", widget: "string"}
      - {label: "end", name: "end", widget: "string"}
      - {label: "Post Body", name: "body", widget: "markdown"}
  - name: "Education-en-GB"
      label: "education-en"
      folder: "src/en-GB/entries/education"
      create: true
      fields:
        - {label: "title", name: "title", widget: "string"}
        - {label: "organization", name: "organization", widget: "string"}
        - {label: "location", name: "location", widget: "string"}
        - {label: "start", name: "start", widget: "string"}
        - {label: "end", name: "end", widget: "string"}